name: workflow 2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - name: Run simple process
        run: |
          echo "Hello from self-hosted runner!"
          sleep 109
